version: '3.3'
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: boten
      POSTGRES_USER: boten 
      POSTGRES_PASSWORD: insecure
    volumes:
      - ~/.ssh/datapunt.key:/root/.ssh/datapunt.key
      - ./backups:/tmp/backups

  api:
    build: .
    ports:
      - "8001:8000"
    links:
      - database
    environment:
      SECRET_KEY: "insecure"
      DJANGO_DEBUG: "True"
      UWSGI_CALLABLE: "application"
      UWSGI_DIE_ON_TERM: "1"
      UWSGI_HARAKIRI: "15"
      UWSGI_HTTP: "0.0.0.0:8000"
      UWSGI_MASTER: "1"
      UWSGI_MODULE: "wsgi:application"
      UWSGI_OFFLOAD_THREADS: "1"
      UWSGI_STATIC_EXPIRES: "/* 3600"
      UWSGI_STATIC_INDEX: "index.html"
      UWSGI_STATIC_MAP: "/waarnemingen/boten/static=/static"
      UWSGI_VACUUM: "1"
