version: '3.3'

volumes:
  db_data:
  db_wal:

services:
  database:
    image: timescale/timescaledb-postgis:1.4.2-pg11
    ports:
      - 5432
    environment:
      - POSTGRES_DB=boten
      - POSTGRES_USER=boten
      - POSTGRES_PASSWORD=insecure
      - PGDATA=/data
      - POSTGRES_INITDB_WALDIR=/wal
    volumes:
      - db_data:/data
      - db_wal:/wal

  app:
    build:
      context: .
      target: app
    image: docker-registry.data.amsterdam.nl/datapunt/waarnemingen-boten:${VERSION:-latest}
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
    volumes:
      - ./src:/src
      - ./deploy:/deploy
    depends_on:
      - database

  dev:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SECRET_KEY=dev
      - PYTHONBREAKPOINT
    volumes:
      - ./src:/src
      - ./deploy:/deploy
    depends_on:
      - database
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: python manage.py runserver 0.0.0.0:8000

  test:
    build:
      context: .
      target: tests
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./deploy:/deploy
    environment:
      - SECRET_KEY=tests
      - DJANGO_SETTINGS_MODULE=config.settings
      - LOG_LEVEL=ERROR
      - PYTEST_ADDOPTS
    depends_on:
      - database
    entrypoint: /deploy/wait-for-it.sh database:5432 --

  import_waternet:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SECRET_KEY=dev
    volumes:
      - ./src:/src
      - ./deploy:/deploy
    depends_on:
      - database
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: python manage.py import_waternet

  scrape_waternet:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    environment:
      - DEBUG=true
      - SECRET_KEY=dev
      - WATERNET_USERNAME
      - WATERNET_PASSWORD
    volumes:
      - ./src:/src
      - ./deploy:/deploy
    depends_on:
      - database
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: python manage.py scrape_waternet
