# Generated by Django 3.0.1 on 2019-12-31 15:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waternet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('status', models.IntegerField()),
                ('sensor', models.CharField(max_length=255)),
                ('lastupdate', models.DateTimeField()),
                ('lastmoved', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('scraped_at',),
            },
        ),
        migrations.CreateModel(
            name='WaternetSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
